CREATE DATABASE Notes;

use Notes;

CREATE TABLE notes (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(500), 
	content TEXT
);

CREATE TABLE labels (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	note_id INT NOT NULL,
	FOREIGN KEY (note_id) REFERENCES notes(id) ON UPDATE CASCADE ON DELETE CASCADE,
	label VARCHAR(100)
);

INSERT INTO notes (title, content)
VALUES
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur laoreet malesuada. Mauris vitae lacinia mauris, a aliquet libero. Sed nisi magna, pretium sed sagittis ac, aliquet id ante. Etiam egestas dapibus blandit. Duis nisl metus, rhoncus sed felis iaculis, imperdiet eleifend felis. Nullam tempus venenatis quam vel porttitor. Aliquam in dolor tincidunt, iaculis enim non, iaculis urna. Aliquam porttitor leo finibus, fermentum orci eget, egestas ligula. Suspendisse sed enim urna. Integer condimentum laoreet aliquam."),
("Etiam sed urna a lorem tristique lacinia.", "Suspendisse auctor fermentum dui, at hendrerit quam dignissim vehicula. Suspendisse cursus neque vitae urna facilisis, a cursus mauris cursus. Vivamus non neque nec erat tempus porta sit amet id nisl. Morbi porta neque id urna commodo aliquam. Aliquam sed volutpat purus. Donec sodales sit amet tellus vulputate elementum. Curabitur blandit scelerisque efficitur. Donec vitae consequat est, id imperdiet nibh. Praesent mi ipsum, pharetra nec dolor eu, hendrerit facilisis nisi. Vestibulum lectus libero, vulputate eu dapibus quis, tempus vel augue. Morbi ut neque lectus. Mauris eget lectus et odio tincidunt ultricies. Vivamus felis nulla, placerat a justo sed, vestibulum lacinia turpis. Pellentesque ac arcu nec dolor suscipit cursus. Praesent eu justo ullamcorper sem hendrerit efficitur eget eget metus. Nam sollicitudin metus in luctus fermentum."),
("Phasellus at nibh nec turpis porta pellentesque ac eget purus.", "Nullam at sem odio. Nullam aliquam rutrum finibus. Fusce auctor augue a nisi mollis ultrices. Maecenas elementum, dui sit amet malesuada porta, leo tortor tempor odio, id tincidunt eros magna sit amet tellus. Praesent venenatis aliquam vulputate. Donec ut enim ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vitae finibus lacus. Aenean pharetra semper nisi non congue. Pellentesque efficitur ex sit amet congue scelerisque."),
("Maecenas at purus ac dolor congue sagittis sit amet id massa.", "Aliquam id massa hendrerit, auctor ex et, fringilla sapien. Vestibulum dictum aliquet lacus, sit amet commodo nibh. Nam vel quam eros. Nunc a augue vitae erat varius posuere in a orci. Vestibulum pharetra lobortis tellus, sed sodales dolor mattis eget. Etiam hendrerit dignissim risus nec euismod. Nullam a posuere arcu, vitae aliquam tortor. Ut ligula ex, sodales eget elit et, lacinia porttitor dui. Pellentesque aliquam fermentum nunc, non ornare diam lobortis eget. Cras sed lorem ante. Integer eget quam id mi porta rutrum sit amet non nisi. Donec et egestas erat, sed vestibulum elit. Curabitur imperdiet leo et diam sagittis malesuada. Nunc auctor nisl justo, sit amet pretium sapien posuere sed."),
("Vestibulum rutrum felis non ligula fermentum, vel fringilla elit vestibulum.", "Sed ac diam id nibh placerat lobortis eu sed dolor. In vel turpis eros. Etiam in viverra tortor. Curabitur mattis, ante eget efficitur finibus, tellus purus volutpat nulla, vel pharetra nisl mi in augue. Phasellus non lectus urna. Fusce vehicula quam non elit congue cursus. Ut aliquet nulla eget justo ullamcorper lobortis. Quisque porta elit mauris, ac malesuada libero consectetur sed. Sed vitae arcu blandit, mollis leo vitae, bibendum nisi. Praesent nunc nisl, faucibus in quam in, elementum gravida quam. In consequat purus eget neque consequat, vel viverra ex varius. Suspendisse augue tortor, fringilla vitae auctor a, congue ut dolor. Vestibulum eu tincidunt nunc. Morbi ornare volutpat lacus rhoncus fringilla. In vel ante euismod ante maximus pellentesque sed eu erat."),
("Aliquam eget est vel ligula pellentesque luctus non rhoncus sapien.", "In luctus, nulla id vulputate semper, ligula turpis iaculis orci, in ultricies ligula mauris eu sapien. Aliquam erat volutpat. Sed eros purus, egestas vitae lorem sit amet, rhoncus aliquam orci. Sed eu tempor justo, semper euismod justo. Etiam elementum sit amet lectus sed sodales. Sed tempor quis lectus vel molestie. Maecenas viverra, ipsum at scelerisque ultricies, urna sem commodo lorem, ut tristique odio nisl vel lectus. Cras laoreet aliquet eleifend. Nam vel nisi volutpat, dapibus turpis sed, mattis ipsum. Mauris blandit lorem quis dolor posuere, id pellentesque sapien egestas. Maecenas eu nisl id ex posuere varius. Vestibulum lacinia imperdiet lacinia. Aenean sollicitudin, neque at ultrices rhoncus, dui massa accumsan tortor, vel vulputate dui urna ut sapien. Nam fermentum porta justo feugiat interdum. Vivamus ultricies leo id sem fringilla, a laoreet dolor commodo."),
("Nam varius massa vel nibh facilisis posuere.", "Mauris lacus velit, rutrum et arcu et, dignissim cursus massa. Nullam tempor egestas diam in molestie. Mauris tincidunt eleifend erat, maximus lobortis justo venenatis quis. Nam commodo vehicula arcu a gravida. Curabitur rutrum pellentesque risus, at molestie libero porta sed. Nullam lacinia velit nec lorem sagittis, id iaculis justo facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In consequat elementum orci, eu dapibus enim porttitor in. Sed at tortor augue. Quisque maximus sem et tortor tincidunt interdum. Quisque imperdiet dolor mi, id convallis est dapibus vitae."),
("Donec suscipit nisl sed leo varius tincidunt.", "In posuere faucibus condimentum. Aliquam nibh neque, condimentum in eros posuere, commodo scelerisque mauris. Nullam nunc sapien, ornare ac sollicitudin eu, dapibus vel leo. Ut sit amet est eu massa porttitor commodo. Sed faucibus tortor dolor, lacinia consectetur eros varius et. Nulla tristique lectus at mi molestie elementum. Phasellus ut luctus turpis. Nam imperdiet risus sed tincidunt malesuada. Maecenas vel nulla non justo pretium ullamcorper. Nulla ex justo, porttitor vitae turpis ac, rhoncus fringilla purus. Maecenas quis sem ullamcorper, dignissim risus in, consequat urna. Vestibulum scelerisque mauris elit, eu vulputate ante tincidunt non. Suspendisse ipsum nisi, porta sed ornare bibendum, bibendum interdum nunc."),
("Aenean non risus sed nulla ultrices faucibus posuere id velit.", "Sed molestie elit in vulputate vehicula. Suspendisse ut leo tempor, varius erat in, feugiat mauris. Nam id varius mi. Sed ac nisl purus. Aliquam nec suscipit ligula, vel consequat sem. In sed tellus quis tellus lacinia lacinia. Donec egestas, diam id egestas viverra, ex libero ullamcorper tellus, a interdum nunc tortor at risus. Pellentesque non eros vel mauris malesuada dictum sit amet sed urna. Cras porta aliquet mi, ut pretium lacus bibendum eu. Duis tortor felis, bibendum vitae ipsum non, fringilla suscipit massa. Nam scelerisque mollis nunc sit amet volutpat. Pellentesque efficitur tempus gravida. Duis at felis odio. Duis a scelerisque ante, vel congue libero. Maecenas mollis diam eros, molestie egestas turpis accumsan sed. Quisque diam risus, vulputate non efficitur in, molestie sed tellus."),
("Nunc laoreet eros quis sagittis placerat.", "Proin eget turpis et nulla condimentum placerat. Sed a posuere mauris, quis tincidunt tortor. Etiam rutrum fermentum maximus. Fusce ultrices nunc vitae finibus mollis. Donec ac vulputate risus. Donec lorem ligula, placerat ac blandit eget, semper ut est. Mauris eu luctus urna. Morbi luctus ante tempus, tempus mauris et, facilisis diam. Proin luctus eros ut mauris tristique, ut interdum magna euismod. Fusce commodo ipsum arcu, eu posuere nisl tristique sed. Vestibulum in odio et sem lobortis molestie eu non urna. Aenean malesuada nulla neque, id maximus enim vulputate a."),
("Suspendisse ut nisl molestie, dapibus tortor sed, pulvinar mauris.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec ipsum in neque posuere euismod pretium id mi. Nulla tincidunt odio eu blandit efficitur. Sed at nisl molestie, scelerisque ex eget, malesuada lacus. Donec commodo ut tortor sit amet posuere. Morbi a dui sed leo porttitor cursus. Sed hendrerit quam nec congue dignissim. Integer porttitor elit ipsum, ut finibus mi tristique quis. Pellentesque rhoncus odio vel diam blandit, id tempus mi varius. Vivamus pretium orci et lacus sollicitudin, eu auctor quam lacinia. Praesent quis diam sit amet augue sagittis mattis et eget sapien."),
("Morbi porta massa a tempor fermentum.", "Duis semper, augue et hendrerit placerat, lorem turpis mollis mi, nec eleifend dolor nunc at augue. Maecenas ac gravida libero. Nullam et gravida est. Pellentesque dapibus varius nibh blandit pretium. Duis nisi elit, tempus consectetur mollis fringilla, pretium quis turpis. Quisque interdum erat convallis dictum egestas. Fusce sodales tortor pulvinar, eleifend lectus eu, eleifend quam. Maecenas lobortis nibh vitae nisl vehicula euismod. Nulla tincidunt diam eget dictum commodo. Pellentesque non ultrices elit. Aliquam gravida ultricies ligula quis tincidunt. Fusce vel nibh vitae odio facilisis tincidunt eu at erat. Pellentesque a gravida nibh."),
("Vivamus eu orci non elit hendrerit dictum.", "Maecenas a lacinia felis. Vestibulum vestibulum ipsum euismod neque laoreet, gravida volutpat sapien feugiat. Nunc sit amet placerat dolor. Nullam id eleifend risus. Nullam dapibus euismod nisl, eget varius quam feugiat ut. Nunc imperdiet aliquam erat, eget finibus augue condimentum non. Quisque tempor eget nisl pretium imperdiet. Praesent et urna suscipit, fermentum odio at, placerat augue. In hac habitasse platea dictumst."),
("Sed eget nulla id urna mollis scelerisque quis non eros.", "Nam facilisis mi vel ipsum aliquam mollis. Aenean dapibus, arcu quis imperdiet dictum, diam mi tempor arcu, nec sodales erat mi et est. Nunc mattis, est a aliquet congue, elit urna ultricies nulla, blandit euismod sem purus quis erat. Morbi eros est, auctor vitae aliquam quis, consequat id velit. Sed hendrerit, elit id mollis cursus, diam dui finibus dolor, non consequat est orci vitae felis. Vivamus elementum placerat risus et elementum. Aliquam id est sit amet libero aliquet posuere ac vel dolor. Sed semper molestie nisi eu convallis. Nullam in ex et augue ultricies egestas. Proin suscipit, tortor ut rutrum maximus, ante lorem mattis nisi, ornare iaculis mauris turpis eu magna. Praesent mauris neque, consequat sed arcu vitae, gravida mollis risus. Maecenas scelerisque quis tellus ac mattis. Suspendisse potenti. Phasellus imperdiet felis et ligula volutpat tincidunt."), 
("Vivamus blandit felis non tellus sagittis, ac vestibulum nisi facilisis.", "Nam id nunc auctor, porttitor odio fringilla, sagittis tellus. Duis interdum augue in dictum luctus. Integer semper quam at lectus consectetur, sed ultricies arcu elementum. Aliquam vulputate at ex nec luctus. Maecenas diam nisi, auctor eget enim in, tincidunt pellentesque ex. Proin lorem ligula, gravida a tortor eget, auctor fringilla velit. Maecenas suscipit, quam sed volutpat dapibus, nulla libero lobortis diam, et semper ligula ante ac lorem. Vestibulum tincidunt velit sit amet enim ultricies, ac porttitor leo porta."),
("Nam maximus dui at odio ultricies hendrerit.", "Pellentesque ultrices, neque et ultrices venenatis, dui nunc elementum nisl, at sodales lectus neque sed nisi. Mauris maximus leo eget nibh malesuada, in condimentum est sodales. Ut at metus est. Vestibulum tristique in nibh eget ultrices. Quisque justo tellus, dignissim id erat nec, imperdiet fermentum odio. Morbi ullamcorper massa ut sem tristique, vitae dignissim nulla egestas. Quisque consectetur venenatis magna non commodo. Nam non augue ac purus hendrerit dignissim. Fusce eleifend, nisl et interdum iaculis, tortor tortor pulvinar odio, sit amet pretium magna ipsum in diam. Nunc congue eget nisi euismod finibus. Duis vitae ipsum dictum turpis blandit eleifend quis id tortor. Fusce eget lobortis leo, vel semper arcu."),
("In scelerisque ipsum quis tempor molestie.", "Sed vehicula in nisi sit amet accumsan. Etiam auctor massa tortor, at tincidunt urna bibendum id. Praesent lobortis lacus vel aliquam rhoncus. Nam dolor sem, porttitor vitae lacinia vel, semper vitae tellus. Donec imperdiet tincidunt sagittis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque vehicula nibh lobortis justo convallis, vitae pellentesque erat interdum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum ac interdum nisl. Vestibulum eu dignissim leo, eu iaculis nisl. Maecenas placerat condimentum ante vitae ultrices."),
("Pellentesque eu ex vel nulla tempus fermentum eu at massa.", "Quisque eu orci arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Proin in felis consectetur, scelerisque sem vel, faucibus magna. Vestibulum a ultricies nunc. Suspendisse pulvinar orci a nunc facilisis venenatis. Vestibulum elementum tortor quis felis rhoncus, et vehicula augue maximus. Nunc ut odio efficitur, pellentesque nisl eu, sagittis justo. Nunc fermentum tincidunt interdum. Nullam ac nulla turpis. Nunc ultricies risus aliquet mauris posuere, at placerat sapien pellentesque. Donec efficitur ex non pulvinar euismod. Quisque sit amet felis gravida, faucibus ipsum id, ullamcorper dui."),
("Sed blandit ex in ultricies sagittis.", "Pellentesque et facilisis neque, placerat condimentum lorem. Proin mi enim, tincidunt nec posuere a, vulputate ut ante. Vestibulum at rutrum metus, nec tristique libero. Maecenas vel vehicula sem. In nulla lectus, consectetur eu sem sed, gravida pharetra dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sagittis ipsum sit amet eleifend venenatis. Sed felis nisi, consectetur nec velit sit amet, venenatis eleifend magna. Nullam dictum ultricies est, ac finibus tellus sagittis viverra. In non posuere nisi."),
("Nulla convallis ex pharetra quam iaculis, id faucibus risus gravida.", "Donec pellentesque est in dolor tincidunt, eget accumsan eros egestas. Sed suscipit faucibus ligula, eget vestibulum tortor dictum ac. Ut congue velit sit amet mattis eleifend. Nulla vitae laoreet nunc. Donec convallis leo id nibh malesuada dictum id sit amet tellus. Nullam quam purus, interdum sed mauris tempor, sagittis ultricies sapien. Quisque interdum laoreet dictum. Sed ut urna elementum, posuere sapien non, tristique nibh. Quisque in diam id tellus suscipit accumsan. Vestibulum bibendum sapien quam, id aliquet dui condimentum nec. Mauris elementum euismod mauris, id auctor eros commodo quis. Morbi vitae sagittis lorem. Sed nisl libero, tristique sed feugiat vitae, rhoncus facilisis nulla. Curabitur ac mollis turpis, sit amet ultrices massa. Pellentesque consequat pretium tortor ac elementum.");

INSERT INTO labels (note_id, label)
VALUES
(1, "cool"),
(1, "easy"),
(2, "TO DO"),
(2, "car"),
(2, "super"),
(4, "cool"),
(4, "cool"),
(4, "interesting"),
(4, "sport"),
(4, "football"),
(5, "easy"),
(6, "super easy"),
(7, "is this a label?"),
(8, "MORE LABELS"),
(9, "i'm bored"),
(10, "lorem ipsum"),
(11, "SUCH NOTE, VERY LABEL"),
(12, "oh crap"),
(13, "reality"),
(14, "startups"),
(15, "software"),
(16, "technology"),
(17, "development"),
(17, "ruby"),
(18, "unit tests");